# Check https://circleci.com/docs/2.0/ for more details
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    environment:
      K3S_VERSION: 0.9.1

    working_directory: ~/k3s-circleci
    steps:
      - checkout
      - run:
          name: Setup k3s
          command: |
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 664" INSTALL_K3S_VERSION=v${K3S_VERSION} sh -
            sleep 5

      - run:
          name: Get k3s nodes
          command: |
            kubectl get node

      - run:
          name: Run busybox
          command: |
            cat <<EOF | kubectl apply -f -
            apiVersion: v1
            kind: Pod
            metadata:
              name: busybox-sleep
            spec:
              containers:
              - name: busybox
                image: busybox
                args:
                - sleep
                - "1000000"
            ---
            apiVersion: v1
            kind: Pod
            metadata:
              name: busybox-sleep-less
            spec:
              containers:
              - name: busybox
                image: busybox
                args:
                - sleep
                - "1000"
            EOF
