# Check https://circleci.com/docs/2.0/ for more details
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    environment:
      K3S_VERSION: v0.8.1 

    working_directory: ~/k3s-circleci
    steps:
      - checkout
      - run:
          name: Setup k3s
          command: |
            curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=${K3S_VERSION} sh -
            sleep 5

      - run:
          name: Get k3s nodes
          command: |
            kubectl get node
