# Check https://circleci.com/docs/2.0/ for more details
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    environment:
      K3S_VERSION: 0.9.1

    working_directory: ~/k3s-circleci
    steps:
      - checkout
      - run:
          name: Setup k3s
          command: |
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 664" INSTALL_K3S_VERSION=v${K3S_VERSION} sh -
            sleep 5

      - run:
          name: Get k3s nodes
          command: |
            kubectl get node

      - run:
          name: Setup tiller
          command: |
            kubectl -n kube-system create serviceaccount tiller
            kubectl create clusterrolebinding tiller \
              --clusterrole=cluster-admin \
              --serviceaccount=kube-system:tiller
            curl -sL https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
            helm init --service-account tiller
            helm repo update
